server:
  port: 8090
spring:
  profiles:
    active: dev
  application:
    name: ${project.artifactId}

---

spring:
  profiles: dev
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1434;databaseName=DocsisDB
    username: sa
    password: Ruhsi@1234
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


