spring:
  profiles:
    active: openshift
  application:
      name: partner-service
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    logfile:
      enabled: true
    httptrace:
      enabled: true

---

spring:
  profiles: dev
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=PartnerDB
    username: sa
    password: Ruhsi@1234
  jpa:
    hibernate:
      ddl-auto: create-drop
base:
  service:
    docsis: http://localhost:8080/
server:
  port: 8090
opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831

---

spring:
  profiles: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
base:
  service:
    docsis: http://localhost:8080/

---

spring:
  profiles: openshift
  datasource:
      url: jdbc:sqlserver://${DATABASE_NAME}:${DATABASE_PORT};databaseName=${DATABASE_SERVICE_PARTNER}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
base:
  service:
    docsis: ${SERVICE_DOCSIS_NAME}/
opentracing:
  jaeger:
    udp-sender:
      host: jaeger-agent
      port: 6831


